database:
  development:
    username: root
    password: root
    host: localhost
    database: mdls
  test:
    username: root
    password: root
    host: localhost
    database: mdls_test
  production:
    username: root
    password: root
    host: localhost
    database: mdls_production
