finder:
  socials:
    - name: facebook
      url: facebook.com/exa
    - name: twitter,
      url: twitter.com/exatrerte
    - name: instagram,
      url: instagram.com/example
  title: "MDLS TEEM"
  description: "Keytar Vice Thundercats, actually disrupt squid gluten-free YOLO you probably haven't heard of them normcore meh. Cold-pressed mixtape Brooklyn, whatever occupy chambray quinoa flexitarian before they sold out flannel meh Carles wayfarers. +1 fanny pack Carles,"
